modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Karashok-Leo/Social-Distance/issues"
license = "MIT"

[[mods]]
modId = "social_distance"
version = "${version}"
displayName = "Social Distance"
authors = "Karashok-Leo"
description = '''
Social Distance
'''
#logoFile = ""

[[dependencies.social_distance]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.social_distance]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"